# Generated by Django 2.1.5 on 2019-01-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main Home Title', max_length=20)),
                ('location', models.CharField(help_text='Main Project Location', max_length=20)),
                ('about_us', models.TextField(help_text='About Project Plus Potentials', max_length=1000)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title for press', max_length=20)),
                ('article', models.TextField(help_text='Enter title for press', max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the project', max_length=1000)),
                ('project_article', models.TextField(help_text='Enter prject article', max_length=1000)),
                ('project_date', models.DateField(blank=True, null=True)),
                ('project_service', models.CharField(blank=True, choices=[('con', 'construction'), ('bui', 'building'), ('rea', 'real estate')], default='og', help_text='What is project service description', max_length=2)),
                ('industry', models.CharField(blank=True, choices=[('og', 'Oil and Gas'), ('ed', 'Education'), ('po', 'Power'), ('el', 'electrical')], default='og', help_text='Client in what Industry?', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(help_text='Title of service', max_length=20)),
                ('service_article', models.TextField(help_text='Enter article here', max_length=100)),
                ('service_slogan', models.CharField(help_text='Slogan for service', max_length=20)),
            ],
            options={
                'ordering': ['-service_title'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of staff', max_length=20)),
                ('position', models.CharField(help_text='Name of Job Position', max_length=20)),
                ('qualification', models.CharField(help_text='Enter Job Qualification', max_length=20)),
                ('cv', models.TextField(help_text='Enter article here', max_length=100)),
                ('service_slogan', models.CharField(help_text='Slogan for service', max_length=20)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
