# Generated by Django 2.1.5 on 2019-01-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_service',
            field=models.CharField(blank=True, choices=[('con', 'construction'), ('bui', 'building'), ('rea', 'real estate')], default='og', help_text='What is project service description', max_length=3),
        ),
    ]
