# Generated by Django 2.1.5 on 2019-01-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0002_auto_20190127_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_article',
            field=models.TextField(help_text='Enter article here', max_length=1000),
        ),
    ]
