# Generated by Django 2.1.5 on 2019-01-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0003_auto_20190127_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_slogan',
            field=models.CharField(help_text='Slogan for service', max_length=100),
        ),
    ]
