# Generated by Django 2.1.5 on 2019-01-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0004_auto_20190127_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='service_slogan',
        ),
        migrations.AlterField(
            model_name='staff',
            name='cv',
            field=models.TextField(help_text='Enter article here', max_length=1000),
        ),
    ]
