# Generated by Django 2.1.5 on 2019-02-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0007_auto_20190208_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_slogan',
        ),
        migrations.AddField(
            model_name='service',
            name='service_summary',
            field=models.CharField(default='We work with you to complete your projects', help_text='Summary for service', max_length=200),
            preserve_default=False,
        ),
    ]
