# Generated by Django 2.1.5 on 2019-02-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0009_auto_20190209_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image2',
            field=models.ImageField(default='projectimages/gallery/None/no-img.jpg', upload_to='projectimages/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image3',
            field=models.ImageField(default='projectimages/gallery/None/no-img.jpg', upload_to='projectimages/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image4',
            field=models.ImageField(default='projectimages/gallery/None/no-img.jpg', upload_to='projectimages/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image5',
            field=models.ImageField(default='projectimages/gallery/None/no-img.jpg', upload_to='projectimages/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image6',
            field=models.ImageField(default='projectimages/gallery/None/no-img.jpg', upload_to='projectimages/gallery/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image7',
            field=models.ImageField(default='projectimages/gallery/None/no-img.jpg', upload_to='projectimages/gallery/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(help_text='Name of staff', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(help_text='Name of Job Position', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='qualification',
            field=models.CharField(help_text='Enter Job Qualification', max_length=100),
        ),
    ]
