# Generated by Django 2.1.5 on 2019-02-10 20:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0012_auto_20190210_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_article',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
    ]
