# Generated by Django 2.1.5 on 2019-02-16 15:45

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0015_auto_20190216_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='press',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image5',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image6',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_image7',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_service',
        ),
        migrations.RemoveField(
            model_name='project',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_summary',
        ),
        migrations.AddField(
            model_name='service',
            name='project',
            field=models.ManyToManyField(related_name='services', to='websiteapp.Project'),
        ),
        migrations.AlterField(
            model_name='home',
            name='about_us',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='press',
            name='article',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_article',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='cv',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='order_of_appearance_on_website',
            field=models.IntegerField(help_text='Enter Desired Order of appearance on website'),
        ),
        migrations.AddField(
            model_name='projectindustry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='websiteapp.Project'),
        ),
    ]
