# Generated by Django 2.1.5 on 2019-02-21 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0016_auto_20190216_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(default='serviceimages/None/no-img.jpg', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='websiteapp.Project'),
        ),
    ]
