# Generated by Django 2.1.5 on 2019-02-23 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0017_auto_20190221_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(default='serviceimages/None/no-img.jpg', upload_to='projectimages/gallery/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='websiteapp.Project'),
        ),
        migrations.AlterField(
            model_name='projectindustry',
            name='industry',
            field=models.CharField(default='', max_length=200),
        ),
    ]
