# Generated by Django 2.1.5 on 2019-02-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0019_auto_20190223_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
