# Generated by Django 2.1.5 on 2019-02-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0022_auto_20190223_0819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectIndustry',
            new_name='Industry',
        ),
    ]
