# Generated by Django 2.1.5 on 2019-02-24 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0023_auto_20190224_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='industry',
            field=models.ForeignKey(default='Building Construction', on_delete=django.db.models.deletion.CASCADE, related_name='Industrieses', to='websiteapp.Industry'),
        ),
    ]
