# Generated by Django 2.1.5 on 2019-02-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0029_projectdetailcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetailcontent',
            name='short_intro',
            field=models.TextField(default='We see your project from start to finish.', max_length=540),
        ),
    ]
