# Generated by Django 2.1.5 on 2019-02-26 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0032_auto_20190226_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectDetailContent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websiteapp.ProjectDetailContent'),
        ),
    ]
