# Generated by Django 2.1.5 on 2019-02-26 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0033_auto_20190226_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ProjectDetailContent',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='websiteapp.ProjectDetailContent'),
        ),
        migrations.AlterField(
            model_name='projectdetailcontent',
            name='main_title',
            field=models.CharField(blank=True, default='Project', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetailcontent',
            name='sub_title',
            field=models.CharField(blank=True, default='Project', max_length=100, null=True),
        ),
    ]
