# Generated by Django 2.1.5 on 2019-02-26 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0034_auto_20190226_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ProjectDetailContent',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='websiteapp.ProjectDetailContent'),
        ),
    ]
