# Generated by Django 2.1.5 on 2019-03-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0036_auto_20190226_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websiteapp.Industry'),
        ),
    ]
