# Generated by Django 2.1.5 on 2019-03-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0037_auto_20190323_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
