# Generated by Django 2.1.5 on 2019-03-24 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0038_project_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_of_service', to='websiteapp.Service'),
        ),
    ]
