# Generated by Django 2.1.5 on 2019-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0039_project_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_title',
            field=models.CharField(help_text='Title of service', max_length=100),
        ),
    ]
