# Generated by Django 2.1.5 on 2019-06-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0042_auto_20190413_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-project_date']},
        ),
        migrations.AlterField(
            model_name='staff',
            name='qualification',
            field=models.CharField(help_text='Enter Job Qualification', max_length=200),
        ),
    ]
