# Generated by Django 2.1.5 on 2019-06-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0043_auto_20190608_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_image1',
            field=models.ImageField(blank=True, null=True, upload_to='serviceimages/'),
        ),
    ]
