# Generated by Django 2.1.5 on 2019-06-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0044_auto_20190608_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(default='img/home/logo-transparent.png', upload_to='projectimages/gallery/'),
        ),
    ]
