# Generated by Django 2.1.5 on 2019-06-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0045_auto_20190608_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
